apiVersion: v1
kind: Secret
metadata:
  name: chatbot-service-secret
  namespace: survivor-apps
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://survivor:survivor-pw@survivor-db-postgresql.data.svc.cluster.local:5432/survivor"