apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # The 'default ""' ensures b64enc always receives a string
  root-user: {{ default "admin" .Values.auth.rootUser | b64enc | quote }}
  root-password: {{ default "password" .Values.auth.rootPassword | b64enc | quote }}