apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui
  namespace: survivor-apps
spec:
  selector:
    app: chatbot-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
